### ISSUE TITLE
Dynamically launch local WSGI/ASGI servers

### ISSUE THREAD

**Issue by azmeuk** [tushuhei/sphinxcontrib-screenshot#25]
This feature request would mostly benefit to the Python projects using sphinxcontrib-screenshot.
I would like to automate the documentation build for my project, and include screenshots of the project.
Currently the README advises to launch my application in a server in parallel of the documentation building.
This works for punctually building the documentation by hand, but it is not really easy to integrate in automated builds (for example in CIs, or with ReadTheDocs (though I am not sure they support playwright at all).)

It would be awesome if sphinxcontrib-screenshot could launch a server in a thread by itself, choose a dynamic port, then kill the server when the documentation is built.

Actually I think this could be achieved with not so much logic code:

- Add a configuration parameter in `conf.py` to dynamically build the WSGI/ASGI application:
  ```python
  from myapp import create_app
  screenshot_app = create_app
   ```
-  Use [portpicker](https://pypi.org/project/portpicker/) to choose a random free port.
- Launch the application in a thread with `wsgiref`. Schematically this would looks like:
  ```python
  import threading
  import wsgiref.simple_server
  port = portpicker.pick_unused_port()
  app = conf.screenshot_app()
  httpd = wsgiref.simple_server.make_server("localhost", port, app)
  thread = threading.Thread(target=httpd.serve_forever)
  thread.start()
  try:
      build_sphinx_doc()
  finally:
      httpd.shutdown()
      thread.join()
  ```
- Then ideally, the base url could become optional (as it will always be `http://localhost:{port}`)
  ```rst
  .. screenshot:: /my/page
  ```
What do you think?

**Comment by tushuhei** [comment]
That's a fantastic suggestion! I'd love to see that feature in the extension. Would you be interested in submitting a pull request?

**Comment by azmeuk** [comment]
Sure!
