### ISSUE TITLE
WSGI applications warning

### ISSUE THREAD

**Issue by azmeuk** [tushuhei/sphinxcontrib-screenshot#29]
I missed it, but with my PR about WSGI apps, sphinx now raises this warning:

```python
pickling environment... WARNING: cannot cache unpickable configuration value: 'screenshot_apps' (because it contains a function, class, or module object) [config.cache]
```

I suggest to change the format of `screenshot_apps` and pass python import references (for instance `my.module:create_app`) as values instead of a callable.

What do you think?

**Comment by tushuhei** [comment]
Thanks for your suggestion. Yes, it sounds good to me.
